# Generated by Django 4.2.7 on 2024-02-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaHub', '0002_post_remove_idea_created_by_remove_project_ideas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='IdeaHub', max_length=255),
        ),
    ]
