# Generated by Django 4.2.7 on 2024-02-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaHub', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
